apiVersion: certmanager.k8s.io/v1alpha
kind: Certificate
metadata:
    name: k8s-multi-com-tls
spec: 
    secretName: k9s-multi-com
    issuerRef: 
        name: letsencrypt-prod
        kind: ClusterIssuer
        commonName: slientcloud.com
        dnsNames:
            - slientcloud.com
            - www.slientcloud.com
        acme:
            config:
                - http01:
                    ingressClass: nginx
                domains:
                    - slientcloud.com
                    - www.slientcloud.com